# Introduction to numerical algorithms
## Practice class 1 - Python and numpy introduction

### Demo 1: Data types

In [1]:
#numeric
a=1
print(type(a))
b=1.0
print(type(b))
c=1.4+2J
print(type(c))

#string
s="Hello"
print(type(s))

#boolean
d=True
print(type(d))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'bool'>


**Working with integers**

In [2]:
a = 3
b = 5
print(a&b)
print('a + b =', a + b)
print('a * b =', a * b)
print('a**b =', a**b)  #Power
print('a / b =', a / b)  #Division (Note: In Python 2, this would give a different result!)
print('a // b =', a // b)  #Integer Division

1
a + b = 8
a * b = 15
a**b = 243
a / b = 0.6
a // b = 0


**Working with floats**

In [3]:
x = 3.
y = 4. #The dot is important, otherwise it will be an integer 
print('x * y = ', x * y)
print('x**y = ', x**y)
print('x/y = ', x/y)
print('x//y = ', x//y) #Works even for float

x * y =  12.0
x**y =  81.0
x/y =  0.75
x//y =  0.0


**Working with complex numbers**

In [ ]:
z1 = 1.+ 2.j
z2 = 2.-1.j
print('z1 + z2 = ', z1 + z2)
print('z1 * z2 = ', z1 * z2)
print('z1 / z2 = ', z1 / z2)
print('z1**z2 = ', z1**z2)  #This also works

#Real part
print(z1.real)
#Imaginary part
print(z1.imag)

**Working with boolean**

In [ ]:
a = True
b = False
print(a)
print(a or b)
print (a and b)
print(not(a))
print(a^b)   # Exclusive OR (XOR)
print(2==a)

**Some fun thing with strings**

In [ ]:
s1 = "hello there!"
print(s1[2:5])
s2 = "I want to \nbreak this line"
print(s2)
s3 = """This is going to be a long string, 
and I want to break it into multiple lines."""
print(s3)

In [ ]:
s4 = "Strings can be concatenated " 
s5 ="like this."
s6 = s4 + s5
print(s6)

#can also be repeated
s7 = "This is a string. "
s8 = s7 * 3
print(s8)

#### escape sequences, in details: https://www.python-ds.com/python-3-escape-sequences )
<table border align="center" style="border-collapse: collapse">
  <thead>
    <tr class="tableheader">
      <th align="left"><b>Escape Sequence</b>&nbsp;</th>
      <th align="left"><b>Meaning</b>&nbsp;</th>
    </thead>
  <tbody valign='baseline'>
    <tr><td align="left" valign="baseline"><code>&#92;<var>newline</var></code></td>
        <td align="left">Ignored</td>
    <tr><td align="left" valign="baseline"><code>&#92;&#92;</code></td>
        <td align="left">Backslash (<code>&#92;</code>)</td>
    <tr><td align="left" valign="baseline"><code>&#92;'</code></td>
        <td align="left">Single quote (<code>'</code>)</td>
    <tr><td align="left" valign="baseline"><code>&#92;"</code></td>
        <td align="left">Double quote (<code>"</code>)</td>
    <tr><td align="left" valign="baseline"><code>&#92;a</code></td>
        <td align="left">ASCII Bell (BEL)</td>
    <tr><td align="left" valign="baseline"><code>&#92;b</code></td>
        <td align="left">ASCII Backspace (BS)</td>
    <tr><td align="left" valign="baseline"><code>&#92;f</code></td>
        <td align="left">ASCII Formfeed (FF)</td>
    <tr><td align="left" valign="baseline"><code>&#92;n</code></td>
        <td align="left">ASCII Linefeed (LF)</td>
    <tr><td align="left" valign="baseline"><code>&#92;r</code></td>
        <td align="left">ASCII Carriage Return (CR)</td>
    <tr><td align="left" valign="baseline"><code>&#92;t</code></td>
        <td align="left">ASCII Horizontal Tab (TAB)</td>
    <tr><td align="left" valign="baseline"><code>&#92;v</code></td>
        <td align="left">ASCII Vertical Tab (VT)</td>
    <tr><td align="left" valign="baseline"><code>&#92;<var>ooo</var></code></td>
        <td align="left">ASCII character with octal value <i>ooo</i></td>
    <tr><td align="left" valign="baseline"><code>&#92;x<var>hh...</var></code></td>
        <td align="left">ASCII character with hex value <i>hh...</i></td></tbody>
</table>

In [ ]:
print("\tapple\n\"banana\"\\'")

how to avoid escape sequencies:

In [ ]:
print("a\bpple",r"a\bpple") #r in front of a string means literal
print(r'C:\some\name')

**How to print numbers?**

In [ ]:
N = 1500
print("The value of N (=",N,") is greater than allowed (1000)")
print("The value of N (=" + str(N) + ") is greater than allowed (1000)")
print("The value of N (=%d) is greater than allowed (%d)" % (N,1000))
print("The value of N (={}) is greater than allowed ({})".format(N,1000))
print("The value of N (={:.2f}) is greater than allowed ({:.2f})".format(N,1000))
#etc.

**Collection of data:**
* list: ordered, changeable, and allow duplicate values
* tuple: ordered and unchangeable
* dict: ordered, changeable and do not allow duplicates
* set: unordered, unchangeable, unindexed, doesn't allow duplicates

In [ ]:
#list
l = ['apple', 'banana', 'cherry']
print(type(l))
print(len(l))


In [ ]:
#tuple
t = ('apple', 'banana', 'cherry')
print(type(t))
print(len(t))
try:
    t[0] = 'orange'
except Exception as e:
    print("Error:", e)

In [ ]:
#dictionary
d = {'name': 'John', 'age': 30, 'city': 'New York'}
print(type(d))
print(len(d))
print(d['name'])

In [ ]:
#set
s = {'apple', 'banana', 'cherry'}
print(type(s))
try:
    s[0] = 'orange'
except Exception as e:
    print("Error:", e)

try:
    print(s[0])
except Exception as e:
    print("Error:", e)

try:
    s.add('apple')
    print(s)
except Exception as e:
    print("Error:", e)

In [ ]:
#Truthiness of different types
print(1==True)
print('a'==True)
print(3==True)
print(1.0==True)
print(1.1==True)

### Demo 2: Control flow

In [ ]:
#different ways to iterate over a list

A=[1,2,3]
for element in A:
    print(element)

for i in range(len(A)):
    print(A[i])

for i,ai in enumerate(A):
    print(i, ai)

In [ ]:
#logic
swithch = 1
if (swithch == 1):
    print("Switch is on")
elif (swithch == 0):
    print("Switch is off")
else:
    print("Switch is in an unknown state")

### Demo 3: List comprehensive

In [ ]:
A=[1,2,3]
sqA = [ai**2 for ai in A]
print(A)
print(sqA)

In [ ]:
#one line if-else
switch = 1
state = "on" if swithch == 1 else "off"
print(state)

### Demo 4: Indexing

In [ ]:
list = [i for i in range(10) ]
list

In [ ]:
#Zero-based indexing
print(list[0])
print(list[4])

#backward indexing
print(list[-1])
print(list[-4])

#slicing
print(list[0:5])
print(list[5:10])
print(list[0:10:2])
print(list[1:-1:3])

### Demo 4: Functions

In [ ]:
def is_even(a):   
    if a % 2 == 0:
        return True
    else:
        return False
print(is_even(2))
print(is_even(3))
print(is_even(-2))
print(is_even(-3))

the `lambda` function

In [ ]:
is_even = lambda a: a % 2 == 0
print(is_even(2))
print(is_even(3))
print(is_even(-2))
print(is_even(-3))

### Numpy, a very brief intro

In [ ]:
# Uncomment the following line to install numpy if you haven't already
#!pip install numpy

import numpy as np

In [ ]:
#vectors and matrices stored in numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
A = np.array([[1, 2, 3], [4, 5, 6]])

# elementwise operations
print(a+b)
print(a-b)
print(a/b)
print(a**2)

# what is it?
# Spoiler: not the matrix product
print(a*a)
print(A*A)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 4 9]
[1 4 9]
[[ 1  4  9]
 [16 25 36]]
14
[14 32]
[[14 32]
 [32 77]]
1
1
[1 2]
[[1 2]
 [4 5]]
[1 2 3]
[1 4]


In [ ]:
# The real matrix product is done with the @ operator
print(a@a)  
print(A@a)
print(A@A.T)  #A.T is the transpose of A

In [ ]:

#indexing as before
print(a[0])
print(A[0, 0])

#also slicing as before
print(a[0:2])
print(A[0:2, 0:2])

#particularly useful for matrices: slicing with a single index
print(A[0])  #first row
print(A[:, 0])  #first column

In [28]:
#universal functions
print(np.sqrt(2))
print(np.sin(np.pi/2))
print(np.log(10))

1.4142135623730951
1.0
2.302585092994046


**Note that they are vectorized and works very efficiently with numpy arrays!**

<span style="color:red">Be careful, always use functions from only one package, numpy is higly recommended!</span>

Avoid the parallel use of e.g. numpy and math  

### Warmup task
1. Create a list containing the square of the first 10 odd numbers.
2. Create a dictionary with two lists containing the odd and the even numbers.


### Task 1
Write a function that finds the minimum in a list!

In [ ]:
def find_min(l):
    #Work here!

#test your code!
print(find_min([-7,-6,4,5,-6,4,-8,6,-5]))

### Task
[Harry Potter books](https://github.com/amephraim/nlp)

Your task will be to analyize the words in Harry Potter and The Sorcerer's Stone.

Download the Harry Potter books from the provided link. Then read in the text of the first book.
1. Split the text to words. Take care of special characters like ,?!" etc. and capital letters.
2. How many different words are in the book? Use set!
3. What are the ten most common words? Use dictionary to story the word counts.