In [1]:
import numpy as np

# Introduction to numerical algorithms
## Practice class 4 - Solving systems of linear equations, Gauss elimination

### System of linear equations

The general form is:
$$\begin{cases}
a_{11} x_1 + a_{12} x_2 +\dots + a_{1n} x_n = b_1 \\
a_{21} x_1 + a_{22} x_2  + \dots + a_{2n} x_n = b_2 \\ 
\vdots\\
a_{m1} x_1 + a_{m2} x_2 + \dots + a_{mn} x_n = b_m,
\end{cases}$$
where $x_1, x_2,\dots,x_n$ are the unknowns, $a_{11},a_{12},\dots,a_{mn}$ are the coefficients of the system, and $b_1,b_2,\dots,b_m$ are the constant terms.

### In matrix form
$$A\mathbf{x}=\mathbf{b},$$
where
$$A=
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix},\quad
\mathbf{x}=
\begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{pmatrix},\quad
\mathbf{b}=
\begin{pmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{pmatrix}.$$

### Gauss elimination

First we create a matrix $(A|b)$. Then we try to make the value below the diagonal zero, and the diagonal one. 

Allowed steps:
* Swapping two rows,
* Multiplying a row by a nonzero number,
* Adding a multiple of one row to another row.

Example:

$$\begin{pmatrix}
1 & 3 & 1 & 9 \\
1 & 1 & -1 & 1 \\
3 & 11 & 5 & 35
\end{pmatrix}\to
\begin{pmatrix}
1 & 3 & 1 & 9 \\
0 & -2 & -2 & -8 \\
0 & 2 & 2 & 8
\end{pmatrix}\to
\begin{pmatrix}
1 & 3 & 1 & 9 \\
0 & -2 & -2 & -8 \\
0 & 0 & 0 & 0
\end{pmatrix}\to
\begin{pmatrix}
1 & 0 & -2 & -3 \\
0 & 1 & 1 & 4 \\
0 & 0 & 0 & 0
\end{pmatrix}$$

The steps:
1. The <b>first</b> row times $-1$ is added to the second row, and the $-3$ times the <b>first</b> row is added to the third row
2. The <b>second</b> row is added to the third row resulting in a row with only zeros, which is a singular case.
3. The <b>second</b> row is multiplied by $-2$ and it is added to the first row multiplied by $-3$. 

##  Warmup
As a warmup we will program the allowed steps of the Gauss elimination and we will perform the previous manipulation

In [10]:
A = np.array([[1,3,1],[1,1,-1],[3,11,5]],dtype=float)
b = np.array([9,1,35],dtype=float)
B = np.column_stack((A,b))
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]


### Warmup Task 1
Write the row swapping algorithm! 

In [3]:
def GE_swap(B,i,j):
    temp = np.copy(B[i,:])
    B[i,:] = np.copy(B[j,:])
    B[j,:] = np.copy(temp)
    #Write your code here
    #Do it in a way that it modifies B itself

In [4]:
# Test your code here!
print(B)
GE_swap(B,1,2)
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]
[[ 1.  3.  1.  9.]
 [ 3. 11.  5. 35.]
 [ 1.  1. -1.  1.]]


### Warmup Task 2
Write a function that multiplies a row of `B` by a non-zero `alpha` number.

In [5]:
def GE_multiply(B,i,alpha):
    B[i,:] = alpha * B[i,:]
    #Write your code here
    #Do it in a way that it modifies B itself

In [6]:
# Test your code here!
print(B)
GE_multiply(B,1,0.4)
print(B)

[[ 1.  3.  1.  9.]
 [ 3. 11.  5. 35.]
 [ 1.  1. -1.  1.]]
[[ 1.   3.   1.   9. ]
 [ 1.2  4.4  2.  14. ]
 [ 1.   1.  -1.   1. ]]


### Warmup Task 3
Write a function that adds `alpha` times row `j` to row `i`.

In [8]:
def GE_add_multiply(B,i,j,alpha):
    B[i,:] = B[i,:] + alpha * B[j,:]
    #Write your code here
    #Do it in a way that it modifies B itself

In [11]:
# Test your code here!
print(B)
GE_add_multiply(B,1,2,-2)
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]
[[  1.   3.   1.   9.]
 [ -5. -21. -11. -69.]
 [  3.  11.   5.  35.]]


### Warmup Task 4
Apply the following steps to your matrix:
1. The <b>first</b> row times $-1$ is added to the second row, and the $-3$ times the <b>first</b> row is added to the third row
2. The <b>second</b> row is added to the third row resulting in a row with only zeros, which is a singular case.
3. The <b>second</b> row is multiplied by $-2$ and it is added to the first row multiplied by $-3$. 

In [13]:
#Here we recreated B so you can start work with the original matrix here
B = np.column_stack((A,b))
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]


In [15]:
#Do your work here
#Step 1
GE_add_multiply(B,1,0,-1)
GE_add_multiply(B,2,0,-3)
#step 2
GE_add_multiply(B,2,1,1)
#Step 3
GE_multiply(B,1,1/2)
GE_add_multiply(B,0,1,-3)
#Check!!!
print(B) # <-- Is it the matrix we had above? 

[[   2.5  -28.5  -33.5 -121.5]
 [  -0.5    6.5    7.5   27.5]
 [  -4.    40.    48.   172. ]]


### Task 1 - Gauss eleimination
First we will write the simplest case of a Gauss elimination.
1. Construct $B=(A|b)$, and get the number of rows.
2. Loop over all the rows.
3. Check if all the elements below the diagonal are zero. If the matrix singular raise an exception, if not swap rows if necessery and continue the elimination.
4. Make the diagonal element one.
5. Loop over the elements below the diagonal and eliminate each element.
6. Contruct the solution based on the following:

Solution is
$$x_i=b_i-\sum_{j=i+1}^{N}b_ix_i$$
If the vector of solution at the beginning is zero $\mathbf{x}=(x_1,x_2,x_3)=(0,0,0)$, then we can rewrite it as:
$$x_i=b_i-\mathbf{b}\mathbf{x},$$
provided we go with $i$ in the reverse order.

In [ ]:
def my_GE(A,b):
    '''Solves the equation A*x=b'''
    A = np.array(A, dtype=float, copy=True)
    b = np.array(b, dtype=float, copy=True)

    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError('A must be a square matrix.')
    if b.shape[0] != A.shape[0]:
        raise ValueError('b must have the same number of rows as A.')

    B = np.column_stack((A, b))
    n = B.shape[0]
    tol = 1e-12

    for i in range(n):
        # If the pivot is zero, try to swap with a lower row
        if abs(B[i, i]) <= tol:
            for j in range(i + 1, n):
                if abs(B[j, i]) > tol:
                    B[[i, j], :] = B[[j, i], :]
                    break
            else:
                raise ValueError('The matrix is singular.')

        # Make the pivot equal to 1
        pivot = B[i, i]
        B[i, :] = B[i, :] / pivot

        # Eliminate entries below the pivot
        for j in range(i + 1, n):
            factor = B[j, i]
            if abs(factor) > tol:
                B[j, :] = B[j, :] - factor * B[i, :]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = B[i, -1] - np.dot(B[i, i + 1 : -1], x[i + 1 :])

    return x


### Test your code!
1. **Try to solve the original equation!**

Recover the result that it is a singular matrix.

2. **Now try with the following equation, for which you should have a solution!**
$$\begin{gather}
3x_1−x_2+4x_3=2\\
17x_1+2x_2+x_3=14\\
x_1+12x_2−7x_3=54
\end{gather}$$

In [29]:
A = np.array([[1,3,1],[1,1,-1],[3,11,5]])
b = np.array([9,1,35])
my_GE(A,b)

[[ 1  3  1  9]
 [ 1  1 -1  1]
 [ 3 11  5 35]]
[[ 1  3  1  9]
 [ 0 -2 -2 -8]
 [ 0  0  0  0]]
No solution


In [46]:
A = np.array([
    [3,-1,4],
    [17, 2, 1],
    [1, 12, -7]
])

b = np.array([2,14,54])

print(my_GE(A,b))

[[ 3 -1  4  2]
 [17  2  1 14]
 [ 1 12 -7 54]]
[[  3  -1   4   2]
 [  0   7 -21   2]
 [  0   0  28  49]]
[0.17857143 5.53571429 1.75      ]


### Task 2 - Partial pivoting
In this task we follow with a more sophisticated way to do the Gauss elimination. One can face problems with the previous implementation by the accumulation of floating point errors. To minimalize this error we will utizile that we can change the order of equations and we will choose the largest absolute value element from blow the diagonal to eliminate with called the pivot element.

Your task is to implement the selection of the pivot element by the modification of point 3. in the previous task. Look for the maximum absolute value element below the diagonal, including the diagonal itself. Perform a row change if the maximal element if not the diagonal. What will be the condition for singularity in terms of the maximal absolute value?

In [37]:
def my_GE_partial_pivot(A,b):
    A = np.array(A, dtype=float, copy=True)
    b = np.array(b, dtype=float, copy=True)

    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError('A must be a square matrix.')
    if b.shape[0] != A.shape[0]:
        raise ValueError('b must have the same number of rows as A.')

    B = np.hstack((A, b.reshape(-1, 1)))
    n = B.shape[0]
    tol = 1e-12

    for i in range(n):
        # Find the pivot row with maximal absolute value in the current column
        pivot_row = i
        pivot_val = abs(B[i, i])
        for j in range(i + 1, n):
            if abs(B[j, i]) > pivot_val:
                pivot_val = abs(B[j, i])
                pivot_row = j

        # Singular if the largest absolute value in the column is zero
        if pivot_val <= tol:
            raise ValueError('The matrix is singular.')

        # Swap rows if necessary
        if pivot_row != i:
            B[[i, pivot_row], :] = B[[pivot_row, i], :]

        # Normalize pivot row
        B[i, :] = B[i, :] / B[i, i]

        # Eliminate entries below the pivot
        for j in range(i + 1, n):
            factor = B[j, i]
            if abs(factor) > tol:
                B[j, :] = B[j, :] - factor * B[i, :]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = B[i, -1] - np.dot(B[i, i + 1 : -1], x[i + 1 :])

    return x


In [38]:
A = np.array([
    [3,-1,4],
    [17, 2, 1],
    [1, 12, -7]
])

b = np.array([2,14,54])

print(my_GE_partial_pivot(A,b))

[0.05901639 5.57377049 1.84918033]


### Task 3 - Full pivoting
You can realize that you have the freedom to choose a pivot element not only from the column below the diagonal but from the whole submatrix below the diagonal. 

Your task is to further modify you previous function to perform the full pivoting.
1. Write the column swap function that swaps columns `i` and `j` in `B`
2. Select the pivot element from the submatrix and store the index of it. 
3. If necessery perform the row and the column swap.
4. Note that with column swaps you change the order of the variables, you need to track it, so create a variable where you track these changes.
5. After constructing the solution by backward substitution reconstruct the original order of the variables!

In [44]:
def my_GE_full_pivot(A,b):
    A = np.array(A, dtype=float, copy=True)
    b = np.array(b, dtype=float, copy=True)

    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError('A must be a square matrix.')
    if b.shape[0] != A.shape[0]:
        raise ValueError('b must have the same number of rows as A.')

    B = np.hstack((A, b.reshape(-1, 1)))
    n = B.shape[0]
    tol = 1e-12

    # Track the order of variables after column swaps
    order = np.arange(n)

    def swap_columns(B, i, j):
        B[:, [i, j]] = B[:, [j, i]]

    for i in range(n):
        # Select the pivot as the largest absolute value in the submatrix B[i:, i:]
        pivot_row = i
        pivot_col = i
        pivot_val = abs(B[i, i])

        for r in range(i, n):
            for c in range(i, n):
                if abs(B[r, c]) > pivot_val:
                    pivot_val = abs(B[r, c])
                    pivot_row = r
                    pivot_col = c

        if pivot_val <= tol:
            raise ValueError('The matrix is singular.')

        # Swap rows if needed
        if pivot_row != i:
            B[[i, pivot_row], :] = B[[pivot_row, i], :]

        # Swap columns if needed
        if pivot_col != i:
            swap_columns(B, i, pivot_col)
            order[[i, pivot_col]] = order[[pivot_col, i]]

        # Normalize pivot row
        B[i, :] = B[i, :] / B[i, i]

        # Eliminate all other rows in the same column
        for r in range(n):
            if r != i:
                factor = B[r, i]
                if abs(factor) > tol:
                    B[r, :] = B[r, :] - factor * B[i, :]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = B[i, -1] - np.dot(B[i, i + 1 : -1], x[i + 1 :])

    # Reconstruct the original order of variables
    x_original = np.zeros(n)
    x_original[order] = x
    return x_original


### Task 4 - Compare the different methods

There are two set of equations below where you can test the efficiency of the different methods. 

In [41]:
A = np.array([
    [1e-20, 1.0, 1.0],
    [1.0,   1.0, 2.0],
    [1.0,   2.0, 3.0]
])

b = np.array([
    2.0,
    4.0,
    6.0
])

print(my_GE(A,b))
print(my_GE_partial_pivot(A,b))
print(my_GE_full_pivot(A,b))
# solution ~[0,0,2]

[[1.e-20 1.e+00 1.e+00 2.e+00]
 [1.e+00 1.e+00 2.e+00 4.e+00]
 [1.e+00 2.e+00 3.e+00 6.e+00]]
[[ 1.e-20  1.e+00  1.e+00  2.e+00]
 [ 0.e+00 -1.e+20 -1.e+20 -2.e+20]
 [ 0.e+00  0.e+00  0.e+00  0.e+00]]
No solution
None


ValueError: The matrix is singular.

In [48]:
A = np.array([
    [ 1.82018118e-08,  1.59970044e+00,  1.16352866e+00],
    [-4.60125295e-08,  4.60403044e-07,  1.42871095e-07],
    [ 7.13592793e-08, -1.63108794e+01,  1.19484660e-04]
], dtype=np.float32)

b = np.array([
     6.68998686e+00,
     1.30340684e-06,
    -3.26214003e+01
], dtype=np.float32)


print(my_GE(A,b))
print(my_GE_partial_pivot(A,b))
print(my_GE_full_pivot(A,b))
#solution [1,2,3]

[[ 1.8201812e-08  1.5997005e+00  1.1635287e+00  6.6899867e+00]
 [-4.6012531e-08  4.6040304e-07  1.4287110e-07  1.3034069e-06]
 [ 7.1359281e-08 -1.6310879e+01  1.1948466e-04 -3.2621399e+01]]
[[1.8201812e-08 1.5997005e+00 1.1635287e+00 6.6899867e+00]
 [3.5527137e-15 4.0438986e+00 2.9412954e+00 1.6911682e+01]
 [1.9839490e-14 0.0000000e+00 1.1863699e+01 3.5591095e+01]]
[12.80938331  1.99999982  2.99999984]
[0.99999928 2.         2.99999978]
[0.9999993  2.         2.99999978]
